### ISSUE TITLE
`feuid.config.js` 配置 `dir` 属性，多级目录不生效

### ISSUE THREAD

**Issue by xinchu** [hnjd-fe/feuid#1]
**如题：**   

配置文件 `feuid.config.js` 中，

`"dir": [ 'package/app/aa' ] `

`feuid --auto`  执行后没有变更相关路径配置文件  

**原因：**  

![image](https://user-images.githubusercontent.com/12138778/58014713-0853d500-7b2c-11e9-9133-89d6be615e42.png)
`+()` 表达式，匹配的是某符合规则的正则表达式。配置 `package/app/aa`， 并不能被解析为路径。

**所以：** 

![image](https://user-images.githubusercontent.com/12138778/58014870-6e405c80-7b2c-11e9-8cb0-08e83a4772ca.png)
` p.allFile`为空  

**建议：**    

将用户配置的 `src` 属性读取后，拼接为配置中文件位置路径，检测路径是否存在，存在做替换逻辑。不存在，抛出异常即可。

**Comment by openjavascript** [comment]
感谢反馈，已在 1.0.15 版本中修复。
请在项目根目录运行命令： yarn remove feuid && yarn add feuid && yarn feuid --auto 
更新包依赖并执行自动化处理

![image](https://user-images.githubusercontent.com/5158593/58032982-39e19600-7b56-11e9-810e-6b17d8e3dd87.png)
